#define RBDSTART 333
#define RBDEND 527
#define PATH "./spikeprot0609.fasta"
#define SEQUENCE "MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT"
#define MAXSC 9
#define MINSC 1

#include<stdio.h>
#include<stdlib.h>
static char samp[] = SEQUENCE;
int main(){
 int n, i, score;
 int malinb[10];
 char name[300];
 char seq[1500];
 char malina[10], malinc[10];
 FILE *fptr;
 if ((fptr = fopen(PATH,"r")) == NULL){
  printf("Error! opening file");
  return 1;
 }for(n=0;n<12140;n++){
  fscanf(fptr, "%s", name);
  fscanf(fptr, "%s", seq);
  score = 0;
  for(i=0;samp[i]!='\0'&&seq[i]!='\0';i++){
   if(seq[i]!=samp[i]&&seq[i]!='X'&&i>=RBDSTART&&i<=RBDEND){
    score++;
    malina[score-1]=samp[i];
    malinb[score-1]= i+1 ;
    malinc[score-1]=seq[i];
   }if(score>=10){
    break;
   }
  }if(score>=MINSC&&score<=MAXSC&&score!=10){
   printf("%d mutations detected, sequence name:\n%s\nmutations: ", score, name);
   for(i=0;i<score;i++){
    printf("%c%d%c ", malina[i], malinb[i], malinc[i]);
   }printf(", original sequence: \n");
   printf("%s\n\n", seq);
  }
 }printf("Count complete\n");
 return 0;
}
